Fix SSM Parms in ServCat, Add except verscheck.py

diff --git a/challenges/workload_security/agentversioncontrol/templates/c1ws_avc_service_catalog.template.yaml b/challenges/workload_security/agentversioncontrol/templates/c1ws_avc_service_catalog.template.yaml
--- a/challenges/workload_security/agentversioncontrol/templates/c1ws_avc_service_catalog.template.yaml
+++ b/challenges/workload_security/agentversioncontrol/templates/c1ws_avc_service_catalog.template.yaml
@@ -12,21 +12,24 @@ Parameters:
     Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
       can include numbers, lowercase letters, uppercase letters, and hyphens (-).
       It cannot start or end with a hyphen (-).
-    Type: String
-    Default: tdc-challenges
+    Type: 'AWS::SSM::Parameter::Value<String>'
+    Default: QSS3BucketName
   QSS3KeyPrefix:
     AllowedPattern: ^[0-9a-zA-Z-/.]*$
     ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
       uppercase letters, hyphens (-), dots(.) and forward slash (/).
-    Default: ""
+    Default: QSS3KeyPrefix
     Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
       can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
       forward slash (/).
-    Type: String
+    Type: 'AWS::SSM::Parameter::Value<String>'
   PublicSubnet1SSMParameter:
     Default: "PublicSubnet1"
     Description: Retrieve the PublicSubnet1 from SSM Parameter Store
-    Type: String
+    Type: 'AWS::SSM::Parameter::Value<String>'
+  LatestAmiId: 
+    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
+    Default: '/aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base'
 
 #######################
 # You can retrieve parameters from SSM, in Parameter of CloudFormation:
@@ -45,7 +48,7 @@ Resources:
   AVCWinInstance:
     Type: AWS::EC2::Instance
     Properties:
-      ImageId: ami-04d183ec0fdc82311
+      ImageId: !Ref 'LatestAmiId'
       InstanceType: t3.medium
       NetworkInterfaces:
         - AssociatePublicIpAddress: true
@@ -55,6 +58,71 @@ Resources:
       Tags:
       - Key: Name
         Value: WinAVCClient
-#      UserData:
-        
+      UserData:
+        Fn::Base64: !Sub |
+         <powershell>
+          [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
+          iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
+          choco install python --version=3.10.4 -y
+          choco install awscli -y
+          pip install requests
+          pip install boto3
+
+          if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
+            Write-Warning "You are not running as an Administrator. Please try again with admin privileges."
+            exit 1
+          }
+
+          $C1WSRegion = [IO.File]::ReadAllText("c:\Projects\C1WSRegion.txt")
+          $managerUrl="https://workload." + C1WSRegion + ".cloudone.trendmicro.com:443/"
+
+          $env:LogPath = "$env:appdata\Trend Micro\Deep Security Agent\installer"
+          New-Item -path $env:LogPath -type directory
+          Start-Transcript -path "$env:LogPath\dsa_deploy.log" -append
+
+          echo "$(Get-Date -format T) - DSA download started"
+          if ( [intptr]::Size -eq 8 ) { 
+            $sourceUrl=-join($managerUrl, "software/agent/Windows/x86_64/20.0.0.3288/agent.msi") }
+          else {
+            $sourceUrl=-join($managerUrl, "software/agent/Windows/i386/20.0.0.3288/agent.msi") }
+          echo "$(Get-Date -format T) - Download Deep Security Agent Package" $sourceUrl
+
+          $ACTIVATIONURL = [IO.File]::ReadAllText("c:\Projects\C1WSActivationURL.txt")
+          $C1WStenantID = [IO.File]::ReadAllText("c:\Projects\C1WStenant.txt")
+          $C1WStokenID = [IO.File]::ReadAllText('c:\Projects\C1WStoken.txt')
+
+          $WebClient = New-Object System.Net.WebClient
+
+          # Add agent version control info
+          $WebClient.Headers.Add("Agent-Version-Control", "off")
+          $WebClient.QueryString.Add("windowsVersion", (Get-CimInstance Win32_OperatingSystem).Version)
+          $WebClient.QueryString.Add("windowsProductType", (Get-CimInstance Win32_OperatingSystem).ProductType)
+
+          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
+
+          Try
+          {
+              $WebClient.DownloadFile($sourceUrl,  "$env:temp\agent.msi")
+          } Catch [System.Net.WebException]
+          {
+                echo " Please check that your Workload Security Manager TLS certificate is signed by a trusted root certificate authority."
+                exit 2;
+          }
+
+          if ( (Get-Item "$env:temp\agent.msi").length -eq 0 ) {
+              echo "Failed to download the Deep Security Agent. Please check if the package is imported into the Workload Security Manager. "
+          exit 1
+          }
+          echo "$(Get-Date -format T) - Downloaded File Size:" (Get-Item "$env:temp\agent.msi").length
+
+          echo "$(Get-Date -format T) - DSA install started"
+          echo "$(Get-Date -format T) - Installer Exit Code:" (Start-Process -FilePath msiexec -ArgumentList "/i $env:temp\agent.msi /qn ADDLOCAL=ALL /l*v `"$env:LogPath\dsa_install.log`"" -Wait -PassThru).ExitCode 
+          echo "$(Get-Date -format T) - DSA activation started"
+
+          Start-Sleep -s 50
+          & $Env:ProgramFiles"\Trend Micro\Deep Security Agent\dsa_control" -r
+          & $Env:ProgramFiles"\Trend Micro\Deep Security Agent\dsa_control" -a $ACTIVATIONURL ""tenantID:"$C1WStenantID" ""token:"$C1WStokenID"
+          Stop-Transcript
+          echo "$(Get-Date -format T) - DSA Deployment Finished" 
+            
 #Outputs:
